function Get_binary_ranking_data = Get_binary_ranking(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   Get_binary_ranking_data = IMPORTFILE(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   Get_binary_ranking_data = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   Get_binary_ranking_data = importfile('ccat_101_binary_ranking_03-Feb-2016_13h03m.txt', 2, 301);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/12/31 10:58:06

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,9,10]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [1,2,3,4,5,6,7,9,10]);
rawStringColumns = string(raw(:, 8));


%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
idx = (rawStringColumns(:, 1) == "<undefined>");
rawStringColumns(idx, 1) = "";

%% Create output variable
Get_binary_ranking_data = table;
Get_binary_ranking_data.subjectID = cell2mat(rawNumericColumns(:, 1));
Get_binary_ranking_data.runtrial = cell2mat(rawNumericColumns(:, 2));
Get_binary_ranking_data.onsettime = cell2mat(rawNumericColumns(:, 3));
Get_binary_ranking_data.ImageLeft = cell2mat(rawNumericColumns(:, 4));
Get_binary_ranking_data.ImageRight = cell2mat(rawNumericColumns(:, 5));
Get_binary_ranking_data.StimNumLeft = cell2mat(rawNumericColumns(:, 6));
Get_binary_ranking_data.StimNumRight = cell2mat(rawNumericColumns(:, 7));
Get_binary_ranking_data.Response = categorical(rawStringColumns(:, 1));
Get_binary_ranking_data.Outcome = cell2mat(rawNumericColumns(:, 8));
Get_binary_ranking_data.RT = cell2mat(rawNumericColumns(:, 9));

